# Base image
FROM node:20-alpine


# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Bundle app source
COPY . . 
RUN npm cache clean --force && rm -rf node_modules && npm install && npm run build:api
CMD [ "node", "dist/apps/api/main.js" ]