version: '3.8'
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      DATABASE_URL: mongodb://admin:password@mongo:27017
      DATABASE_NAME: mydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/usr/src/app/apps/api
      - ./package.json:/usr/src/app/package.json
      - ./libs:/usr/src/app/libs
    depends_on:
      - redis         # Mapea el puerto 5432 al host
      - mongo
  redis:
    image: redis:latest      # Usa la última versión estable de Redis
    restart: always
    ports:
      - "6379:6379"          # Mapea el puerto 6379 al host
  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      - redis
  mongo:
    image: mongo:latest # Imagen oficial de MongoDB
    restart: always
    ports:
      - "27017:27017" # Exponer el puerto 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Usuario por defecto
      MONGO_INITDB_ROOT_PASSWORD: password # Contraseña por defecto

  mongo-express:
    image: mongo-express:latest # Interfaz web para MongoDB
    restart: always
    ports:
      - "8081:8081" # Exponer el puerto 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo # Nombre del servicio MongoDB
    depends_on:
      - mongo
