version: '3.8'
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: npm run start:api
    environment:
      DATABASE_URL: postgresql://pm:pm@db:5432/pmdb?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/usr/src/app/apps/api
      - ./package.json:/usr/src/app/package.json
      - ./libs:/usr/src/app/libs
    depends_on:
      - redis         # Mapea el puerto 5432 al host
  redis:
    image: redis:latest      # Usa la última versión estable de Redis
    restart: always
    ports:
      - "6379:6379"          # Mapea el puerto 6379 al host
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
