# Base image
FROM node:20-alpine


# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY prisma ./prisma/

# Bundle app source
COPY . . 

RUN npm cache clean --force && rm -rf node_modules && npm install
RUN npm run prisma:generate

# Start the server using the production build
CMD [ "npm", "start" ]